import {
  MousePointerClick,
  Webhook,
  Clock,
  Globe,
  GitBranch,
  Variable,
  Timer,
  Code2,
  MessageSquare,
  Mail,
  Table2,
  Sheet,
  Send,
  MessageCircle,
  FileText,
  Kanban,
  GitPullRequest,
  Users,
  Repeat,
  GitMerge,
  Workflow,
  MailPlus,
  Calendar,
  CheckSquare,
  Bug,
  Sparkles,
  Database,
  Filter,
  MessageCircleMore,
} from "lucide-react";

export const NODE_REGISTRY = {
  manualTrigger: {
    label: "Manual Trigger",
    category: "Triggers",
    color: "#6366f1",
    icon: MousePointerClick,
    description: "Starts the workflow only when you click Run now.",
  },
  webhookTrigger: {
    label: "Webhook",
    category: "Triggers",
    color: "#6366f1",
    icon: Webhook,
    description: "Starts the workflow when an external service calls its URL.",
  },
  scheduleTrigger: {
    label: "Schedule",
    category: "Triggers",
    color: "#6366f1",
    icon: Clock,
    description: "Starts the workflow on a cron schedule.",
  },
  httpRequest: {
    label: "HTTP Request",
    category: "Actions",
    color: "#0ea5e9",
    icon: Globe,
    description: "Calls an external API (GET/POST/PUT/PATCH/DELETE).",
  },
  slackMessage: {
    label: "Slack Message",
    category: "Actions",
    color: "#611f69",
    icon: MessageSquare,
    description: "Posts a message via a Slack Incoming Webhook URL.",
  },
  discordMessage: {
    label: "Discord Message",
    category: "Actions",
    color: "#5865f2",
    icon: MessageSquare,
    description: "Posts a message via a Discord Webhook URL.",
  },
  emailSend: {
    label: "Send Email",
    category: "Actions",
    color: "#ea580c",
    icon: Mail,
    description: "Sends an email via your own SMTP credentials.",
  },
  airtableCreateRecord: {
    label: "Airtable: Create Record",
    category: "Actions",
    color: "#fcb400",
    icon: Table2,
    description: "Creates a record in an Airtable base/table.",
  },
  googleSheetsAppendRow: {
    label: "Google Sheets: Append Row",
    category: "Actions",
    color: "#0f9d58",
    icon: Sheet,
    description: "Appends a row to a Google Sheet via a service account.",
  },
  telegramMessage: {
    label: "Telegram Message",
    category: "Actions",
    color: "#26a5e4",
    icon: Send,
    description: "Sends a message via a Telegram bot.",
  },
  twilioSms: {
    label: "Twilio: Send SMS",
    category: "Actions",
    color: "#f22f46",
    icon: MessageCircle,
    description: "Sends an SMS text message via Twilio.",
  },
  notionCreatePage: {
    label: "Notion: Create Page",
    category: "Actions",
    color: "#e5e5e5",
    icon: FileText,
    description: "Creates a page in a Notion database.",
  },
  trelloCreateCard: {
    label: "Trello: Create Card",
    category: "Actions",
    color: "#0079bf",
    icon: Kanban,
    description: "Creates a card in a Trello list.",
  },
  githubCreateIssue: {
    label: "GitHub: Create Issue",
    category: "Actions",
    color: "#f0f6fc",
    icon: GitPullRequest,
    description: "Opens a new issue in a GitHub repository.",
  },
  hubspotCreateContact: {
    label: "HubSpot: Create Contact",
    category: "Actions",
    color: "#ff7a59",
    icon: Users,
    description: "Creates a contact in HubSpot CRM.",
  },
  mailchimpAddSubscriber: {
    label: "Mailchimp: Add Subscriber",
    category: "Actions",
    color: "#ffe01b",
    icon: MailPlus,
    description: "Adds a subscriber to a Mailchimp audience.",
  },
  googleCalendarCreateEvent: {
    label: "Google Calendar: Create Event",
    category: "Actions",
    color: "#4285f4",
    icon: Calendar,
    description: "Creates an event on a Google Calendar via a service account.",
  },
  gmailSendEmail: {
    label: "Gmail: Send Email",
    category: "Actions",
    color: "#d93025",
    icon: Mail,
    description: "Sends mail via a Gmail API service account user.",
  },
  googleDriveCreateFile: {
    label: "Google Drive: Create File",
    category: "Actions",
    color: "#34a853",
    icon: Sheet,
    description: "Creates a file in Google Drive with the provided content.",
  },
  microsoftTeamsMessage: {
    label: "Microsoft Teams: Send Message",
    category: "Actions",
    color: "#6264a7",
    icon: MessageSquare,
    description: "Posts a message to a Teams incoming webhook.",
  },
  clickUpCreateTask: {
    label: "ClickUp: Create Task",
    category: "Actions",
    color: "#7b68ee",
    icon: CheckSquare,
    description: "Creates a task in a ClickUp list.",
  },
  gitlabCreateIssue: {
    label: "GitLab: Create Issue",
    category: "Actions",
    color: "#fc6d26",
    icon: GitPullRequest,
    description: "Creates an issue in a GitLab project.",
  },
  linearCreateIssue: {
    label: "Linear: Create Issue",
    category: "Actions",
    color: "#5e6ad2",
    icon: Bug,
    description: "Creates an issue in a Linear team.",
  },
  shopifyCreateCustomer: {
    label: "Shopify: Create Customer",
    category: "Actions",
    color: "#96bf48",
    icon: Users,
    description: "Creates a customer in Shopify from a workflow payload.",
  },
  stripeCreateCustomer: {
    label: "Stripe: Create Customer",
    category: "Actions",
    color: "#635bff",
    icon: Users,
    description: "Creates a Stripe customer record from workflow data.",
  },
  asanaCreateTask: {
    label: "Asana: Create Task",
    category: "Actions",
    color: "#f06a6a",
    icon: CheckSquare,
    description: "Creates a task in an Asana project.",
  },
  jiraCreateIssue: {
    label: "Jira: Create Issue",
    category: "Actions",
    color: "#0052cc",
    icon: Bug,
    description: "Creates an issue in a Jira Cloud project.",
  },
  openaiGenerateText: {
    label: "OpenAI: Generate Text",
    category: "Actions",
    color: "#10a37f",
    icon: Sparkles,
    description: "Generates text from a prompt using OpenAI.",
  },
  postgresQuery: {
    label: "Postgres: Run Query",
    category: "Actions",
    color: "#336791",
    icon: Database,
    description: "Runs a parameterized SQL query against a Postgres database.",
  },
  twilioWhatsapp: {
    label: "WhatsApp Message",
    category: "Actions",
    color: "#25d366",
    icon: MessageCircleMore,
    description: "Sends a WhatsApp message via Twilio.",
  },
  ifCondition: {
    label: "If / Else",
    category: "Logic",
    color: "#f59e0b",
    icon: GitBranch,
    description: "Branches the workflow based on a condition.",
  },
  setVariable: {
    label: "Set Variable",
    category: "Logic",
    color: "#f59e0b",
    icon: Variable,
    description: "Stores a value for later nodes to use.",
  },
  delay: {
    label: "Delay",
    category: "Logic",
    color: "#f59e0b",
    icon: Timer,
    description: "Pauses execution for a set number of milliseconds.",
  },
  filter: {
    label: "Filter",
    category: "Logic",
    color: "#f59e0b",
    icon: Filter,
    description: "Stops this branch here if a condition is false — doesn't error the run.",
  },
  code: {
    label: "Code",
    category: "Advanced",
    color: "#8b5cf6",
    icon: Code2,
    description: "Runs custom JS in a secure sandbox.",
  },
  loop: {
    label: "Loop / Map",
    category: "Advanced",
    color: "#8b5cf6",
    icon: Repeat,
    description: "Runs JS code once per item in an array, returning the results.",
  },
  merge: {
    label: "Merge",
    category: "Advanced",
    color: "#8b5cf6",
    icon: GitMerge,
    description: "Combines named variables set by earlier branches into one object.",
  },
  executeWorkflow: {
    label: "Execute Workflow",
    category: "Advanced",
    color: "#8b5cf6",
    icon: Workflow,
    description: "Runs another one of your workflows as a sub-workflow.",
  },
};

export const CATEGORIES = ["Triggers", "Actions", "Logic", "Advanced"];

const SELF_HOSTED = import.meta.env.VITE_SELF_HOSTED === "true";
const ALL_NODE_TYPES = new Set(Object.keys(NODE_REGISTRY));

export const PLAN_NODE_TYPES = SELF_HOSTED ? {
  free: ALL_NODE_TYPES,
  starter: ALL_NODE_TYPES,
  pro: ALL_NODE_TYPES,
} : {
  free: new Set([
    "manualTrigger", "webhookTrigger", "scheduleTrigger", "httpRequest",
    "slackMessage", "discordMessage", "emailSend", "ifCondition",
    "setVariable", "filter",
  ]),
  starter: new Set([
    "manualTrigger", "webhookTrigger", "scheduleTrigger", "httpRequest",
    "slackMessage", "discordMessage", "emailSend", "gmailSendEmail",
    "microsoftTeamsMessage", "airtableCreateRecord", "googleSheetsAppendRow",
    "googleDriveCreateFile", "telegramMessage", "twilioSms", "notionCreatePage",
    "trelloCreateCard", "githubCreateIssue", "gitlabCreateIssue", "hubspotCreateContact",
    "mailchimpAddSubscriber", "googleCalendarCreateEvent", "twilioWhatsapp",
    "asanaCreateTask", "clickUpCreateTask", "ifCondition", "setVariable", "filter", "delay",
  ]),
  pro: new Set(Object.keys(NODE_REGISTRY)),
};
